<?php

$flag = array(
    "France" => "flag-icon-fr",
    "Japon" => "flag-icon-jp",
    "Chine" => "flag-icon-cn",
    "Corée du Sud" => "flag-icon-kr",
    "Australie" => "flag-icon-au",
    "Qatar" => "flag-icon-qa",
    "Irak" => "flag-icon-iq",
    "Émirats arabes unis" => "flag-icon-ae",
    "Iran" => "flag-icon-ir",
    "Arabie Saoudite" => "flag-icon-sa",
    "Ouzbékistan" => "flag-icon-uz",
    "Syrie" => "flag-icon-sy",
    "Yémen" => "flag-icon-ye",
    "Liban" => "flag-icon-lb",
    "Palestinien" => "flag-icon-ps",
    "Jordanie" => "flag-icon-jo",
    "Koweït" => "flag-icon-kw",
    "Oman" => "flag-icon-om",
    "Bahreïn" => "flag-icon-bh",
    "Thaïlande" => "flag-icon-th",
    "Vietnam" => "flag-icon-vn",
    "Malaisie" => "flag-icon-my",
    "Indonésie" => "flag-icon-id",
    "Singapour" => "flag-icon-sg",
    "Philippines" => "flag-icon-ph",
    "Myanmar" => "flag-icon-mm",
    "Cambodge" => "flag-icon-kh",
    "Laos" => "flag-icon-la",
    "Brunei" => "flag-icon-bn",
    "Timor-Leste" => "flag-icon-tl",
    "Mongolie" => "flag-icon-mn",
    "Népal" => "flag-icon-np",
    "Bhoutan" => "flag-icon-bt",
    "Bangladesh" => "flag-icon-bd",
    "Sri Lanka" => "flag-icon-lk",
    "Maldives" => "flag-icon-mv",
    "Pakistan" => "flag-icon-pk",
    "Afghanistan" => "flag-icon-af",
    "Tadjikistan" => "flag-icon-tj",
    "Turkménistan" => "flag-icon-tm",
    "Kazakhstan" => "flag-icon-kz",
    "Kirghizistan" => "flag-icon-kg",
    "Azerbaïdjan" => "flag-icon-az",
    "Géorgie" => "flag-icon-ge",
    "Arménie" => "flag-icon-am",
    "Turquie" => "flag-icon-tr",
    "Chypre" => "flag-icon-cy",
    "Grèce" => "flag-icon-gr",
    "Bulgarie" => "flag-icon-bg",
    "Roumanie" => "flag-icon-ro",
    "Moldavie" => "flag-icon-md",
    "Ukraine" => "flag-icon-ua",
    "Biélorussie" => "flag-icon-by",
    "Russie" => "flag-icon-ru",
    "Estonie" => "flag-icon-ee",
    "Lettonie" => "flag-icon-lv",
    "Lituanie" => "flag-icon-lt",
    "Pologne" => "flag-icon-pl",
    "République tchèque" => "flag-icon-cz",
    "Slovaquie" => "flag-icon-sk",
    "Hongrie" => "flag-icon-hu",
    "Slovénie" => "flag-icon-si",
    "Croatie" => "flag-icon-hr",
    "Bosnie-Herzégovine" => "flag-icon-ba",
    "Serbie" => "flag-icon-rs",
    "Monténégro" => "flag-icon-me",
    "Kosovo" => "flag-icon-xk",
    "Macédoine du Nord" => "flag-icon-mk",
    "Albanie" => "flag-icon-al",
);

function getFlag($country)
{
    global $flag;
    return $flag[$country];
}